### ISSUE TITLE
Does jmx-exporter could monitor existing hbase cluster?

### ISSUE THREAD

**Issue by regardfs** [BasPH/hbase-prometheus-monitoring#1]
I have a hbase cluster managed by  ambari
Could jmx-exporter could monitor existing hbase cluster?

**Comment by BasPH** [comment]
Yes no problem. Edit the config in Ambari and not the config on disk, otherwise Ambari will override it.

**Comment by regardfs** [comment]
@BasPH， I have done this by export ENV in hbase env config zone，and inject JMx-exporter as an independent agent In Hbase startup script。
